FROM nikolaik/python-nodejs:python3.8-nodejs14

RUN npm install -g \
  autoprefixer@^9.7.0 \
  cssnano@^4.1.10 \
  postcss-cli@^6.1.3

ENV PATH="/root/.local/bin:$PATH"
ENV NODE_PATH="/usr/lib/node_modules"
